### ISSUE TITLE
เขียน Project Proposal

### ISSUE THREAD

**Issue by tchoopojcharoen** [Coxsys/3D-Navigation-Software-for-Autonomous-Forklift#1]
- [ ] ที่มาและความสำคัญ
- [ ] วัตถุประสงค์
- [x] ระยะเวลาดำเนินงาน
- [x] สถานที่ปฎิบัติงาน
- [x] วิธีการดำเนินงาน/ แผนงาน (Gantt) รายวัน/สัปดาห์
- [x] งบประมาณ 
- [x] การประเมินโครงการและการวัดผล
- [x] ผลที่คาดว่าจะได้รับ

**Comment by tchoopojcharoen** [comment]
เขียนกรอกที่ tick ไว้  Template อยู่ใน Google Drive 
@SweiLz  ถ้าทำเป็น Latex Template  ด้วย ก็ดีนะ แต่ไม่จำเป็นครับ

**Comment by SweiLz** [comment]
เขียนแบบคร่าวๆน่าจะประมาณนี้ แต่จะต้องลงรายละเอียดของแต่ละขั้นตอนให้ชัดเจน
